DROP TABLE IF EXISTS temp_bag_pand; 
CREATE TABLE temp_bag_pand AS
SELECT * 
FROM bag_pand
TABLESAMPLE BERNOULLI(0.5); 
DROP TABLE IF EXISTS temp_bag_vbo; 
CREATE TABLE temp_bag_vbo AS
SELECT * 
FROM bag_vbo
TABLESAMPLE BERNOULLI(0.5);
DROP TABLE IF EXISTS temp_cdwaste; 
CREATE TABLE temp_cdwaste AS
SELECT * 
FROM cdwaste
TABLESAMPLE BERNOULLI(0.5);